name: Send Invoice Reminder Emails

on:
  schedule:
    - cron: '15 6 * * *'  # Runs daily at 11:45 AM IST (6:15 AM UTC)
  workflow_dispatch:     # Allows manual run from GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SHEET_URL: ${{ secrets.SHEET_URL }}
        run: |
          python main.py
